name: ci

on:
  pull_request:
    branches: [master]
    paths:
      - 'go_version/**'     # trigger only if PR touches go_version
  push:
    branches: [master]
    paths:
      - 'go_version/**'     # optional: enable for direct pushes too

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Run our tests
        run: cd go_version && go test -cover ./...

      - name: Install gosec
        run: cd go_version && go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Security Check
        run: cd go_version && gosec ./...
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Check formatting
        run: cd go_version && test -z $(go fmt ./...)

      - name: Install staticcheck
        run: cd go_version && go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: cd go_version && staticcheck ./...
